### ISSUE TITLE
Add ToDo

### ISSUE THREAD

**Issue by sjbeatle** [sjbeatle/git-bits-dun#5]
## Story
As a user, I want to be able to add an item to my todo list, so that I can remember to do it later today.

## Acceptance Criteria
- [x] Single-Line Text Input component for users to add a todo item
- [x] Ability to submit the todo
  - [x] Simple validation: submit disabled until text is valid
  - [x] Text is properly encoded
- [x] Todo added to mongodb
- [x] Success alert text
- [x] Error alert text
