### ISSUE TITLE
Give ToDo Priority

### ISSUE THREAD

**Issue by sjbeatle** [sjbeatle/git-bits-dun#7]
## Story
As a user, I want to be able to give a todo priority, so that I can see how urgent they are.

## Acceptance Criteria
- [x] Priority checkbox added to submit form
- [x] Todos flagged as priorities are shown at the top of the todo list
  - [x] Following the same ascending/descending rules
